local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = 'telescope find files' })
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = 'telescope grep string' })
vim.keymap.set('n', '<leader>vh', builtin.help_tags, { desc = 'telescope help tags' })
--vim.keymap.set('n', '<C-q>', builtin.help_tags, { desc = 'telescope help tags' })
